[package]
name = "lshell"
version = "1.0.6"
edition = "2021"
description = "A fast and feature-rich shell written in Rust" 
authors = ["jmaxdev"]
license = "UPL-1.0" 

[dependencies]
crossterm = "0.28"
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
dirs = "5.0"
chrono = "0.4"
self_update = { version = "0.41", features = ["archive-zip", "archive-tar", "compression-flate2", "compression-zip-deflate"] }
serde_json = "1.0"
